<testsuites id="" name="" tests="3" failures="3" skipped="0" errors="0" time="30.936">
<testsuite name="tests/index.test.ts" timestamp="1627638833757" hostname="" tests="1" failures="1" skipped="0" time="30.01" errors="0">
<testcase name="basic test" classname="[chromium] › tests/index.test.ts:3:1 › basic test" time="30.01">
<failure message="index.test.ts:3:1 basic test" type="FAILURE">
  [chromium] › tests/index.test.ts:3:1 › basic test ================================================

    Timeout of 30000ms exceeded.

    Pending operations:
      - page.innerText at tests/index.test.ts:5:27

    page.innerText: Protocol error (Runtime.callFunctionOn): Target closed.
    =========================== logs ===========================
      retrieving innerText from "data-testid=application"
    ============================================================

      3 | test('basic test', async ({page}) => {
      4 |   await page.goto('http://localhost:8000/docs');
    > 5 |   const name = await page.innerText('data-testid=application');
        |                           ^
      6 |   expect(name).toBe('Application');
      7 | });

        at /Users/vs/workspace/playwright-test/playwright-frontend/tests/index.test.ts:5:27
        at WorkerRunner._runTestWithBeforeHooks (/Users/vs/workspace/playwright-test/playwright-frontend/node_modules/@playwright/test/lib/test/workerRunner.js:390:7)

</failure>
</testcase>
</testsuite>
<testsuite name="tests/index.test.ts" timestamp="1627638833757" hostname="" tests="1" failures="1" skipped="0" time="30.018" errors="0">
<testcase name="basic test" classname="[firefox] › tests/index.test.ts:3:1 › basic test" time="30.018">
<failure message="index.test.ts:3:1 basic test" type="FAILURE">
  [firefox] › tests/index.test.ts:3:1 › basic test =================================================

    Timeout of 30000ms exceeded.

    Pending operations:
      - page.innerText at tests/index.test.ts:5:27

    page.innerText: Protocol error (Runtime.callFunction): Target closed.undefined
    =========================== logs ===========================
      retrieving innerText from "data-testid=application"
    ============================================================

      3 | test('basic test', async ({page}) => {
      4 |   await page.goto('http://localhost:8000/docs');
    > 5 |   const name = await page.innerText('data-testid=application');
        |                           ^
      6 |   expect(name).toBe('Application');
      7 | });

        at /Users/vs/workspace/playwright-test/playwright-frontend/tests/index.test.ts:5:27
        at WorkerRunner._runTestWithBeforeHooks (/Users/vs/workspace/playwright-test/playwright-frontend/node_modules/@playwright/test/lib/test/workerRunner.js:390:7)

</failure>
</testcase>
</testsuite>
<testsuite name="tests/index.test.ts" timestamp="1627638833757" hostname="" tests="1" failures="1" skipped="0" time="30.01" errors="0">
<testcase name="basic test" classname="[webkit] › tests/index.test.ts:3:1 › basic test" time="30.01">
<failure message="index.test.ts:3:1 basic test" type="FAILURE">
  [webkit] › tests/index.test.ts:3:1 › basic test ==================================================

    Timeout of 30000ms exceeded.

    Pending operations:
      - page.innerText at tests/index.test.ts:5:27

    page.innerText: Protocol error (Runtime.callFunctionOn): The page has been closed.
    =========================== logs ===========================
      retrieving innerText from "data-testid=application"
    ============================================================

      3 | test('basic test', async ({page}) => {
      4 |   await page.goto('http://localhost:8000/docs');
    > 5 |   const name = await page.innerText('data-testid=application');
        |                           ^
      6 |   expect(name).toBe('Application');
      7 | });

        at /Users/vs/workspace/playwright-test/playwright-frontend/tests/index.test.ts:5:27
        at WorkerRunner._runTestWithBeforeHooks (/Users/vs/workspace/playwright-test/playwright-frontend/node_modules/@playwright/test/lib/test/workerRunner.js:390:7)

</failure>
</testcase>
</testsuite>
</testsuites>